CREATE DATABASE QLDT_PK
GO
USE QLDT_PK
GO
CREATE TABLE TAIKHOAN (
    MATK VARCHAR(20) NOT NULL, -- CREATE AUTO
    USERNAME VARCHAR(50), -- CHECK USERNAME THEO GROUP
    PW VARCHAR(100), -- MÃ HÓA + salt
    CONSTRAINT PK_TK PRIMARY KEY (MATK)
)

-- GR ADMIN(00): CONTROL ALL
-- GR NHÂN VIÊN(01): HỖ TRỢ KHÁCH HÀNG XỬ LÝ ĐƠN HÀNG
-- GR KHÁCH HÀNG(02): NGƯỜI DÙNG
CREATE TABLE GRTK (
    MAGR INT IDENTITY NOT NULL,
    TEN VARCHAR(50), -- TÊN GR
    CODEGR CHAR(2),
    CONSTRAINT PK_GR PRIMARY KEY (MAGR) 
)

CREATE TABLE THONGTINTAIKHOAN (
    MATK VARCHAR(20) NOT NULL, -- CREATE AUTO
    HOTEN NVARCHAR(50), -- HỌ TÊN
    NGSINH DATE, -- NGÀY SINH
    GTINH BIT, -- 1: NAM, 0: NỮ, NULL: CHƯA BIẾT(QUY VỀ 0)
    NGTAO DATE, -- NGÀY TẠO
    EMAIL VARCHAR(50), -- ĐỊA CHỈ EMAIL
    SDT VARCHAR(11), -- SDT
    DCHI NVARCHAR(50), -- ĐỊA CHỈ NHÀ / ĐỊA CHỈ GIAO
    CONSTRAINT PK_TTTK PRIMARY KEY (MATK),
	CONSTRAINT FK_TTTK_TAIKHOAN FOREIGN KEY (MATK) REFERENCES TAIKHOAN(MATK)
)

CREATE TABLE KHACHHANG (
	MAKH VARCHAR(20) NOT NULL, -- CREATE AUTO
    MAGR INT NOT NULL,
    CONSTRAINT PK_KH PRIMARY KEY (MAKH),
	CONSTRAINT FK_KH_GRTK FOREIGN KEY (MAGR) REFERENCES GRTK(MAGR)
)

CREATE TABLE NHANVIEN (
    MANV VARCHAR(20) NOT NULL, -- CREATE AUTO
    MAGR INT NOT NULL,
    CONSTRAINT PK_NV PRIMARY KEY (MANV),
	CONSTRAINT FK_NHANVIEN_GRTK FOREIGN KEY (MAGR) REFERENCES GRTK(MAGR)
)

CREATE TABLE LOAISP (
    MALOAI VARCHAR(20) NOT NULL,
    TENLOAI NVARCHAR(50),
    CONSTRAINT PK_LSP PRIMARY KEY (MALOAI)
)

CREATE TABLE SANPHAM (
	MASP VARCHAR(20) NOT NULL, -- CREATE AUTO
    MALOAI VARCHAR(20) NOT NULL,
    TENSP NVARCHAR(50), -- TÊN SẢN PHẨM
    MOTA NVARCHAR(MAX), -- MÔ TẢ
    SOLUONG INT, -- SỐ LƯỢNG TỒN KHO
    DONGIA FLOAT, -- ĐƠN GIÁ
    NSX NVARCHAR(30), -- NHÀ SẢN XUẤT
    CONSTRAINT PK_SP PRIMARY KEY (MASP),
	CONSTRAINT FK_SP_LSP FOREIGN KEY (MALOAI) REFERENCES LOAISP(MALOAI)
)

CREATE TABLE DONGIA (
    MADG INT IDENTITY NOT NULL, -- MÃ ĐƠN GIÁ
    MASP VARCHAR(20) NOT NULL,
    GIA FLOAT, -- GIÁ
    NGCAPNHAT DATETIME, -- NGÀY CẬP NHẬT - LẤY NGÀY MỚI NHẤT
    CONSTRAINT PK_DG PRIMARY KEY (MADG,MASP),
	CONSTRAINT FK_DG_SP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
)

CREATE TABLE HOADON (
    MAHD VARCHAR(20) NOT NULL, -- CREATE AUTO
	MAKH VARCHAR(20) NOT NULL, 
	MANV VARCHAR(20) NOT NULL, 
    NGTAO DATE, -- NGÀY TẠO HÓA ĐƠN
    DONGIA FLOAT, -- TỔNG (SỐ LƯỢNG * ĐƠN GIÁ)
    TINHTRANG NVARCHAR(50), -- CHƯA GIAO, ĐÃ GIAO
    CONSTRAINT PK_HD PRIMARY KEY (MAHD),
	CONSTRAINT FK_HD_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
	CONSTRAINT FK_HD_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
)

CREATE TABLE CHITIETHD (
    MAHD VARCHAR(20) NOT NULL,
	MASP VARCHAR(20) NOT NULL,
    SOLUONG INT, -- SỐ LƯỢNG > 0
    CONSTRAINT PK_CTHD PRIMARY KEY (MAHD,MASP),
	CONSTRAINT FK_CTHD_HD FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
	CONSTRAINT FK_CTHD_SP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
)
GO